clean: true
podspec: PrivacyKit.podspec
# author: It Haz Fire LLC
# author_url: https://ithazfire.com
# github_url: https://github.com/ithazfire/PrivacyKit
# module_version: 1.0.0
# module: PrivacyKit
# framework_root: PrivacyKit/
documentation: Guides/*.md
copyright: Copyright © 2020 It Haz Fire.
# min_acl: private
# output: docs
